require('dotenv').load()

const {
  TWITTER_KEY,
  TWITTER_SECRET,
  ACCESS_SECRET,
  ACCESS_TOKEN,
  TWITTER_HANDLE,
  REDIS_HOSTNAME,
  REDIS_PASSWORD,
  REDIS_PORT
} = process.env

module.exports = {
  TWITTER_KEY,
  TWITTER_SECRET,
  ACCESS_SECRET,
  ACCESS_TOKEN,
  TWITTER_HANDLE,
  REDIS_HOSTNAME,
  REDIS_PASSWORD,
  REDIS_PORT
}
